query ProjectsPage($projectId: ID!) {
  projectTaskSections(where: { projectID: $projectId }) {
    edges {
      node {
        id
        name
        projectId
        projectTasks {
          id
          taskId
          projectId
          projectTaskSectionId
          project {
            ...ProjectFragment
          }
          task {
            ...TaskForListFragment
          }
          createdAt
          updatedAt
        }
        createdAt
        updatedAt
      }
    }
  }
  projectTaskColumns(where: { projectID: $projectId }) {
    edges {
      node {
        ...ProjectTaskColumnFragment
      }
    }
  }
  projectTaskListStatus(where: { projectID: $projectId }) {
    ...ProjectTaskListStatusFragment
  }
}
