// Generated by `yarn new:queryMock`
import { server } from '../../server'
import { favoriteProjectIdsQuery } from '../favoriteProjectIds'
import type { Options } from './type'

export const setFavoriteProjectIdsQuery = (options: Options) => {
  server.use(favoriteProjectIdsQuery(options))
}
