export const TASK_LIST_SORT_STATUS_TYPE_NONE = 1 as const
export const TASK_LIST_SORT_STATUS_TYPE_DUE_DATE = 2 as const
export const TASK_LIST_SORT_STATUS_TYPE_LIKES = 3 as const
export const TASK_LIST_SORT_STATUS_TYPE_ALPHABETICAL = 4 as const
export const TASK_LIST_SORT_STATUS_TYPE_PROJECT = 5 as const
export const TASK_LIST_SORT_STATUS_TYPE_ASSIGNEE = 6 as const

export type TaskListSortStatusType =
  | typeof TASK_LIST_SORT_STATUS_TYPE_NONE
  | typeof TASK_LIST_SORT_STATUS_TYPE_DUE_DATE
  | typeof TASK_LIST_SORT_STATUS_TYPE_LIKES
  | typeof TASK_LIST_SORT_STATUS_TYPE_ALPHABETICAL
  | typeof TASK_LIST_SORT_STATUS_TYPE_PROJECT
  | typeof TASK_LIST_SORT_STATUS_TYPE_ASSIGNEE
