// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"project-management-demo-backend/ent/archivedworkspaceactivity"
	"project-management-demo-backend/ent/archivedworkspaceactivitytask"
	"project-management-demo-backend/ent/schema/ulid"
	"project-management-demo-backend/ent/task"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ArchivedWorkspaceActivityTask is the model entity for the ArchivedWorkspaceActivityTask schema.
type ArchivedWorkspaceActivityTask struct {
	config `json:"-"`
	// ID of the ent.
	ID ulid.ID `json:"id,omitempty"`
	// ArchivedWorkspaceActivityID holds the value of the "archived_workspace_activity_id" field.
	ArchivedWorkspaceActivityID ulid.ID `json:"archived_workspace_activity_id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID ulid.ID `json:"task_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArchivedWorkspaceActivityTaskQuery when eager-loading is set.
	Edges ArchivedWorkspaceActivityTaskEdges `json:"edges"`
}

// ArchivedWorkspaceActivityTaskEdges holds the relations/edges for other nodes in the graph.
type ArchivedWorkspaceActivityTaskEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// ArchivedWorkspaceActivity holds the value of the archivedWorkspaceActivity edge.
	ArchivedWorkspaceActivity *ArchivedWorkspaceActivity `json:"archivedWorkspaceActivity,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ArchivedWorkspaceActivityTaskEdges) TaskOrErr() (*Task, error) {
	if e.loadedTypes[0] {
		if e.Task == nil {
			// The edge task was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: task.Label}
		}
		return e.Task, nil
	}
	return nil, &NotLoadedError{edge: "task"}
}

// ArchivedWorkspaceActivityOrErr returns the ArchivedWorkspaceActivity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ArchivedWorkspaceActivityTaskEdges) ArchivedWorkspaceActivityOrErr() (*ArchivedWorkspaceActivity, error) {
	if e.loadedTypes[1] {
		if e.ArchivedWorkspaceActivity == nil {
			// The edge archivedWorkspaceActivity was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: archivedworkspaceactivity.Label}
		}
		return e.ArchivedWorkspaceActivity, nil
	}
	return nil, &NotLoadedError{edge: "archivedWorkspaceActivity"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ArchivedWorkspaceActivityTask) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case archivedworkspaceactivitytask.FieldCreatedAt, archivedworkspaceactivitytask.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case archivedworkspaceactivitytask.FieldID, archivedworkspaceactivitytask.FieldArchivedWorkspaceActivityID, archivedworkspaceactivitytask.FieldTaskID:
			values[i] = new(ulid.ID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ArchivedWorkspaceActivityTask", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ArchivedWorkspaceActivityTask fields.
func (awat *ArchivedWorkspaceActivityTask) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case archivedworkspaceactivitytask.FieldID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				awat.ID = *value
			}
		case archivedworkspaceactivitytask.FieldArchivedWorkspaceActivityID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field archived_workspace_activity_id", values[i])
			} else if value != nil {
				awat.ArchivedWorkspaceActivityID = *value
			}
		case archivedworkspaceactivitytask.FieldTaskID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				awat.TaskID = *value
			}
		case archivedworkspaceactivitytask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				awat.CreatedAt = value.Time
			}
		case archivedworkspaceactivitytask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				awat.UpdatedAt = value.Time
			}
		}
	}
	return nil
}

// QueryTask queries the "task" edge of the ArchivedWorkspaceActivityTask entity.
func (awat *ArchivedWorkspaceActivityTask) QueryTask() *TaskQuery {
	return (&ArchivedWorkspaceActivityTaskClient{config: awat.config}).QueryTask(awat)
}

// QueryArchivedWorkspaceActivity queries the "archivedWorkspaceActivity" edge of the ArchivedWorkspaceActivityTask entity.
func (awat *ArchivedWorkspaceActivityTask) QueryArchivedWorkspaceActivity() *ArchivedWorkspaceActivityQuery {
	return (&ArchivedWorkspaceActivityTaskClient{config: awat.config}).QueryArchivedWorkspaceActivity(awat)
}

// Update returns a builder for updating this ArchivedWorkspaceActivityTask.
// Note that you need to call ArchivedWorkspaceActivityTask.Unwrap() before calling this method if this ArchivedWorkspaceActivityTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (awat *ArchivedWorkspaceActivityTask) Update() *ArchivedWorkspaceActivityTaskUpdateOne {
	return (&ArchivedWorkspaceActivityTaskClient{config: awat.config}).UpdateOne(awat)
}

// Unwrap unwraps the ArchivedWorkspaceActivityTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (awat *ArchivedWorkspaceActivityTask) Unwrap() *ArchivedWorkspaceActivityTask {
	tx, ok := awat.config.driver.(*txDriver)
	if !ok {
		panic("ent: ArchivedWorkspaceActivityTask is not a transactional entity")
	}
	awat.config.driver = tx.drv
	return awat
}

// String implements the fmt.Stringer.
func (awat *ArchivedWorkspaceActivityTask) String() string {
	var builder strings.Builder
	builder.WriteString("ArchivedWorkspaceActivityTask(")
	builder.WriteString(fmt.Sprintf("id=%v", awat.ID))
	builder.WriteString(", archived_workspace_activity_id=")
	builder.WriteString(fmt.Sprintf("%v", awat.ArchivedWorkspaceActivityID))
	builder.WriteString(", task_id=")
	builder.WriteString(fmt.Sprintf("%v", awat.TaskID))
	builder.WriteString(", created_at=")
	builder.WriteString(awat.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(awat.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ArchivedWorkspaceActivityTasks is a parsable slice of ArchivedWorkspaceActivityTask.
type ArchivedWorkspaceActivityTasks []*ArchivedWorkspaceActivityTask

func (awat ArchivedWorkspaceActivityTasks) config(cfg config) {
	for _i := range awat {
		awat[_i].config = cfg
	}
}
