// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"project-management-demo-backend/ent/archivedtaskactivity"
	"project-management-demo-backend/ent/archivedtaskactivitytask"
	"project-management-demo-backend/ent/schema/ulid"
	"project-management-demo-backend/ent/task"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ArchivedTaskActivityTask is the model entity for the ArchivedTaskActivityTask schema.
type ArchivedTaskActivityTask struct {
	config `json:"-"`
	// ID of the ent.
	ID ulid.ID `json:"id,omitempty"`
	// ArchivedTaskActivityID holds the value of the "archived_task_activity_id" field.
	ArchivedTaskActivityID ulid.ID `json:"archived_task_activity_id,omitempty"`
	// TaskID holds the value of the "task_id" field.
	TaskID ulid.ID `json:"task_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ArchivedTaskActivityTaskQuery when eager-loading is set.
	Edges ArchivedTaskActivityTaskEdges `json:"edges"`
}

// ArchivedTaskActivityTaskEdges holds the relations/edges for other nodes in the graph.
type ArchivedTaskActivityTaskEdges struct {
	// Task holds the value of the task edge.
	Task *Task `json:"task,omitempty"`
	// ArchivedTaskActivity holds the value of the archivedTaskActivity edge.
	ArchivedTaskActivity *ArchivedTaskActivity `json:"archivedTaskActivity,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TaskOrErr returns the Task value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ArchivedTaskActivityTaskEdges) TaskOrErr() (*Task, error) {
	if e.loadedTypes[0] {
		if e.Task == nil {
			// The edge task was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: task.Label}
		}
		return e.Task, nil
	}
	return nil, &NotLoadedError{edge: "task"}
}

// ArchivedTaskActivityOrErr returns the ArchivedTaskActivity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ArchivedTaskActivityTaskEdges) ArchivedTaskActivityOrErr() (*ArchivedTaskActivity, error) {
	if e.loadedTypes[1] {
		if e.ArchivedTaskActivity == nil {
			// The edge archivedTaskActivity was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: archivedtaskactivity.Label}
		}
		return e.ArchivedTaskActivity, nil
	}
	return nil, &NotLoadedError{edge: "archivedTaskActivity"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ArchivedTaskActivityTask) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case archivedtaskactivitytask.FieldCreatedAt, archivedtaskactivitytask.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case archivedtaskactivitytask.FieldID, archivedtaskactivitytask.FieldArchivedTaskActivityID, archivedtaskactivitytask.FieldTaskID:
			values[i] = new(ulid.ID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type ArchivedTaskActivityTask", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ArchivedTaskActivityTask fields.
func (atat *ArchivedTaskActivityTask) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case archivedtaskactivitytask.FieldID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				atat.ID = *value
			}
		case archivedtaskactivitytask.FieldArchivedTaskActivityID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field archived_task_activity_id", values[i])
			} else if value != nil {
				atat.ArchivedTaskActivityID = *value
			}
		case archivedtaskactivitytask.FieldTaskID:
			if value, ok := values[i].(*ulid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field task_id", values[i])
			} else if value != nil {
				atat.TaskID = *value
			}
		case archivedtaskactivitytask.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				atat.CreatedAt = value.Time
			}
		case archivedtaskactivitytask.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				atat.UpdatedAt = value.Time
			}
		}
	}
	return nil
}

// QueryTask queries the "task" edge of the ArchivedTaskActivityTask entity.
func (atat *ArchivedTaskActivityTask) QueryTask() *TaskQuery {
	return (&ArchivedTaskActivityTaskClient{config: atat.config}).QueryTask(atat)
}

// QueryArchivedTaskActivity queries the "archivedTaskActivity" edge of the ArchivedTaskActivityTask entity.
func (atat *ArchivedTaskActivityTask) QueryArchivedTaskActivity() *ArchivedTaskActivityQuery {
	return (&ArchivedTaskActivityTaskClient{config: atat.config}).QueryArchivedTaskActivity(atat)
}

// Update returns a builder for updating this ArchivedTaskActivityTask.
// Note that you need to call ArchivedTaskActivityTask.Unwrap() before calling this method if this ArchivedTaskActivityTask
// was returned from a transaction, and the transaction was committed or rolled back.
func (atat *ArchivedTaskActivityTask) Update() *ArchivedTaskActivityTaskUpdateOne {
	return (&ArchivedTaskActivityTaskClient{config: atat.config}).UpdateOne(atat)
}

// Unwrap unwraps the ArchivedTaskActivityTask entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (atat *ArchivedTaskActivityTask) Unwrap() *ArchivedTaskActivityTask {
	tx, ok := atat.config.driver.(*txDriver)
	if !ok {
		panic("ent: ArchivedTaskActivityTask is not a transactional entity")
	}
	atat.config.driver = tx.drv
	return atat
}

// String implements the fmt.Stringer.
func (atat *ArchivedTaskActivityTask) String() string {
	var builder strings.Builder
	builder.WriteString("ArchivedTaskActivityTask(")
	builder.WriteString(fmt.Sprintf("id=%v", atat.ID))
	builder.WriteString(", archived_task_activity_id=")
	builder.WriteString(fmt.Sprintf("%v", atat.ArchivedTaskActivityID))
	builder.WriteString(", task_id=")
	builder.WriteString(fmt.Sprintf("%v", atat.TaskID))
	builder.WriteString(", created_at=")
	builder.WriteString(atat.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(atat.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ArchivedTaskActivityTasks is a parsable slice of ArchivedTaskActivityTask.
type ArchivedTaskActivityTasks []*ArchivedTaskActivityTask

func (atat ArchivedTaskActivityTasks) config(cfg config) {
	for _i := range atat {
		atat[_i].config = cfg
	}
}
