// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-management-demo-backend/ent/activitytype"
	"project-management-demo-backend/ent/archivedtaskactivity"
	"project-management-demo-backend/ent/archivedtaskactivitytask"
	"project-management-demo-backend/ent/schema/ulid"
	"project-management-demo-backend/ent/teammate"
	"project-management-demo-backend/ent/workspace"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArchivedTaskActivityCreate is the builder for creating a ArchivedTaskActivity entity.
type ArchivedTaskActivityCreate struct {
	config
	mutation *ArchivedTaskActivityMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetActivityTypeID sets the "activity_type_id" field.
func (atac *ArchivedTaskActivityCreate) SetActivityTypeID(u ulid.ID) *ArchivedTaskActivityCreate {
	atac.mutation.SetActivityTypeID(u)
	return atac
}

// SetTeammateID sets the "teammate_id" field.
func (atac *ArchivedTaskActivityCreate) SetTeammateID(u ulid.ID) *ArchivedTaskActivityCreate {
	atac.mutation.SetTeammateID(u)
	return atac
}

// SetWorkspaceID sets the "workspace_id" field.
func (atac *ArchivedTaskActivityCreate) SetWorkspaceID(u ulid.ID) *ArchivedTaskActivityCreate {
	atac.mutation.SetWorkspaceID(u)
	return atac
}

// SetCreatedAt sets the "created_at" field.
func (atac *ArchivedTaskActivityCreate) SetCreatedAt(t time.Time) *ArchivedTaskActivityCreate {
	atac.mutation.SetCreatedAt(t)
	return atac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (atac *ArchivedTaskActivityCreate) SetNillableCreatedAt(t *time.Time) *ArchivedTaskActivityCreate {
	if t != nil {
		atac.SetCreatedAt(*t)
	}
	return atac
}

// SetUpdatedAt sets the "updated_at" field.
func (atac *ArchivedTaskActivityCreate) SetUpdatedAt(t time.Time) *ArchivedTaskActivityCreate {
	atac.mutation.SetUpdatedAt(t)
	return atac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (atac *ArchivedTaskActivityCreate) SetNillableUpdatedAt(t *time.Time) *ArchivedTaskActivityCreate {
	if t != nil {
		atac.SetUpdatedAt(*t)
	}
	return atac
}

// SetID sets the "id" field.
func (atac *ArchivedTaskActivityCreate) SetID(u ulid.ID) *ArchivedTaskActivityCreate {
	atac.mutation.SetID(u)
	return atac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (atac *ArchivedTaskActivityCreate) SetNillableID(u *ulid.ID) *ArchivedTaskActivityCreate {
	if u != nil {
		atac.SetID(*u)
	}
	return atac
}

// SetTeammate sets the "teammate" edge to the Teammate entity.
func (atac *ArchivedTaskActivityCreate) SetTeammate(t *Teammate) *ArchivedTaskActivityCreate {
	return atac.SetTeammateID(t.ID)
}

// SetActivityType sets the "activityType" edge to the ActivityType entity.
func (atac *ArchivedTaskActivityCreate) SetActivityType(a *ActivityType) *ArchivedTaskActivityCreate {
	return atac.SetActivityTypeID(a.ID)
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (atac *ArchivedTaskActivityCreate) SetWorkspace(w *Workspace) *ArchivedTaskActivityCreate {
	return atac.SetWorkspaceID(w.ID)
}

// AddArchivedTaskActivityTaskIDs adds the "archivedTaskActivityTasks" edge to the ArchivedTaskActivityTask entity by IDs.
func (atac *ArchivedTaskActivityCreate) AddArchivedTaskActivityTaskIDs(ids ...ulid.ID) *ArchivedTaskActivityCreate {
	atac.mutation.AddArchivedTaskActivityTaskIDs(ids...)
	return atac
}

// AddArchivedTaskActivityTasks adds the "archivedTaskActivityTasks" edges to the ArchivedTaskActivityTask entity.
func (atac *ArchivedTaskActivityCreate) AddArchivedTaskActivityTasks(a ...*ArchivedTaskActivityTask) *ArchivedTaskActivityCreate {
	ids := make([]ulid.ID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return atac.AddArchivedTaskActivityTaskIDs(ids...)
}

// Mutation returns the ArchivedTaskActivityMutation object of the builder.
func (atac *ArchivedTaskActivityCreate) Mutation() *ArchivedTaskActivityMutation {
	return atac.mutation
}

// Save creates the ArchivedTaskActivity in the database.
func (atac *ArchivedTaskActivityCreate) Save(ctx context.Context) (*ArchivedTaskActivity, error) {
	var (
		err  error
		node *ArchivedTaskActivity
	)
	atac.defaults()
	if len(atac.hooks) == 0 {
		if err = atac.check(); err != nil {
			return nil, err
		}
		node, err = atac.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ArchivedTaskActivityMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = atac.check(); err != nil {
				return nil, err
			}
			atac.mutation = mutation
			if node, err = atac.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(atac.hooks) - 1; i >= 0; i-- {
			if atac.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = atac.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, atac.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (atac *ArchivedTaskActivityCreate) SaveX(ctx context.Context) *ArchivedTaskActivity {
	v, err := atac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atac *ArchivedTaskActivityCreate) Exec(ctx context.Context) error {
	_, err := atac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atac *ArchivedTaskActivityCreate) ExecX(ctx context.Context) {
	if err := atac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (atac *ArchivedTaskActivityCreate) defaults() {
	if _, ok := atac.mutation.CreatedAt(); !ok {
		v := archivedtaskactivity.DefaultCreatedAt()
		atac.mutation.SetCreatedAt(v)
	}
	if _, ok := atac.mutation.UpdatedAt(); !ok {
		v := archivedtaskactivity.DefaultUpdatedAt()
		atac.mutation.SetUpdatedAt(v)
	}
	if _, ok := atac.mutation.ID(); !ok {
		v := archivedtaskactivity.DefaultID()
		atac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atac *ArchivedTaskActivityCreate) check() error {
	if _, ok := atac.mutation.ActivityTypeID(); !ok {
		return &ValidationError{Name: "activity_type_id", err: errors.New(`ent: missing required field "ArchivedTaskActivity.activity_type_id"`)}
	}
	if _, ok := atac.mutation.TeammateID(); !ok {
		return &ValidationError{Name: "teammate_id", err: errors.New(`ent: missing required field "ArchivedTaskActivity.teammate_id"`)}
	}
	if _, ok := atac.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace_id", err: errors.New(`ent: missing required field "ArchivedTaskActivity.workspace_id"`)}
	}
	if _, ok := atac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ArchivedTaskActivity.created_at"`)}
	}
	if _, ok := atac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ArchivedTaskActivity.updated_at"`)}
	}
	if _, ok := atac.mutation.TeammateID(); !ok {
		return &ValidationError{Name: "teammate", err: errors.New(`ent: missing required edge "ArchivedTaskActivity.teammate"`)}
	}
	if _, ok := atac.mutation.ActivityTypeID(); !ok {
		return &ValidationError{Name: "activityType", err: errors.New(`ent: missing required edge "ArchivedTaskActivity.activityType"`)}
	}
	if _, ok := atac.mutation.WorkspaceID(); !ok {
		return &ValidationError{Name: "workspace", err: errors.New(`ent: missing required edge "ArchivedTaskActivity.workspace"`)}
	}
	return nil
}

func (atac *ArchivedTaskActivityCreate) sqlSave(ctx context.Context) (*ArchivedTaskActivity, error) {
	_node, _spec := atac.createSpec()
	if err := sqlgraph.CreateNode(ctx, atac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ulid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (atac *ArchivedTaskActivityCreate) createSpec() (*ArchivedTaskActivity, *sqlgraph.CreateSpec) {
	var (
		_node = &ArchivedTaskActivity{config: atac.config}
		_spec = &sqlgraph.CreateSpec{
			Table: archivedtaskactivity.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: archivedtaskactivity.FieldID,
			},
		}
	)
	_spec.OnConflict = atac.conflict
	if id, ok := atac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := atac.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: archivedtaskactivity.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := atac.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: archivedtaskactivity.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if nodes := atac.mutation.TeammateIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   archivedtaskactivity.TeammateTable,
			Columns: []string{archivedtaskactivity.TeammateColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: teammate.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeammateID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := atac.mutation.ActivityTypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   archivedtaskactivity.ActivityTypeTable,
			Columns: []string{archivedtaskactivity.ActivityTypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: activitytype.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ActivityTypeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := atac.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   archivedtaskactivity.WorkspaceTable,
			Columns: []string{archivedtaskactivity.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: workspace.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.WorkspaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := atac.mutation.ArchivedTaskActivityTasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   archivedtaskactivity.ArchivedTaskActivityTasksTable,
			Columns: []string{archivedtaskactivity.ArchivedTaskActivityTasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: archivedtaskactivitytask.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ArchivedTaskActivity.Create().
//		SetActivityTypeID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArchivedTaskActivityUpsert) {
//			SetActivityTypeID(v+v).
//		}).
//		Exec(ctx)
//
func (atac *ArchivedTaskActivityCreate) OnConflict(opts ...sql.ConflictOption) *ArchivedTaskActivityUpsertOne {
	atac.conflict = opts
	return &ArchivedTaskActivityUpsertOne{
		create: atac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ArchivedTaskActivity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (atac *ArchivedTaskActivityCreate) OnConflictColumns(columns ...string) *ArchivedTaskActivityUpsertOne {
	atac.conflict = append(atac.conflict, sql.ConflictColumns(columns...))
	return &ArchivedTaskActivityUpsertOne{
		create: atac,
	}
}

type (
	// ArchivedTaskActivityUpsertOne is the builder for "upsert"-ing
	//  one ArchivedTaskActivity node.
	ArchivedTaskActivityUpsertOne struct {
		create *ArchivedTaskActivityCreate
	}

	// ArchivedTaskActivityUpsert is the "OnConflict" setter.
	ArchivedTaskActivityUpsert struct {
		*sql.UpdateSet
	}
)

// SetActivityTypeID sets the "activity_type_id" field.
func (u *ArchivedTaskActivityUpsert) SetActivityTypeID(v ulid.ID) *ArchivedTaskActivityUpsert {
	u.Set(archivedtaskactivity.FieldActivityTypeID, v)
	return u
}

// UpdateActivityTypeID sets the "activity_type_id" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsert) UpdateActivityTypeID() *ArchivedTaskActivityUpsert {
	u.SetExcluded(archivedtaskactivity.FieldActivityTypeID)
	return u
}

// SetTeammateID sets the "teammate_id" field.
func (u *ArchivedTaskActivityUpsert) SetTeammateID(v ulid.ID) *ArchivedTaskActivityUpsert {
	u.Set(archivedtaskactivity.FieldTeammateID, v)
	return u
}

// UpdateTeammateID sets the "teammate_id" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsert) UpdateTeammateID() *ArchivedTaskActivityUpsert {
	u.SetExcluded(archivedtaskactivity.FieldTeammateID)
	return u
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *ArchivedTaskActivityUpsert) SetWorkspaceID(v ulid.ID) *ArchivedTaskActivityUpsert {
	u.Set(archivedtaskactivity.FieldWorkspaceID, v)
	return u
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsert) UpdateWorkspaceID() *ArchivedTaskActivityUpsert {
	u.SetExcluded(archivedtaskactivity.FieldWorkspaceID)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *ArchivedTaskActivityUpsert) SetCreatedAt(v time.Time) *ArchivedTaskActivityUpsert {
	u.Set(archivedtaskactivity.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsert) UpdateCreatedAt() *ArchivedTaskActivityUpsert {
	u.SetExcluded(archivedtaskactivity.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ArchivedTaskActivityUpsert) SetUpdatedAt(v time.Time) *ArchivedTaskActivityUpsert {
	u.Set(archivedtaskactivity.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsert) UpdateUpdatedAt() *ArchivedTaskActivityUpsert {
	u.SetExcluded(archivedtaskactivity.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ArchivedTaskActivity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(archivedtaskactivity.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *ArchivedTaskActivityUpsertOne) UpdateNewValues() *ArchivedTaskActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(archivedtaskactivity.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(archivedtaskactivity.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.UpdatedAt(); exists {
			s.SetIgnore(archivedtaskactivity.FieldUpdatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.ArchivedTaskActivity.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *ArchivedTaskActivityUpsertOne) Ignore() *ArchivedTaskActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArchivedTaskActivityUpsertOne) DoNothing() *ArchivedTaskActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArchivedTaskActivityCreate.OnConflict
// documentation for more info.
func (u *ArchivedTaskActivityUpsertOne) Update(set func(*ArchivedTaskActivityUpsert)) *ArchivedTaskActivityUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArchivedTaskActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityTypeID sets the "activity_type_id" field.
func (u *ArchivedTaskActivityUpsertOne) SetActivityTypeID(v ulid.ID) *ArchivedTaskActivityUpsertOne {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.SetActivityTypeID(v)
	})
}

// UpdateActivityTypeID sets the "activity_type_id" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsertOne) UpdateActivityTypeID() *ArchivedTaskActivityUpsertOne {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.UpdateActivityTypeID()
	})
}

// SetTeammateID sets the "teammate_id" field.
func (u *ArchivedTaskActivityUpsertOne) SetTeammateID(v ulid.ID) *ArchivedTaskActivityUpsertOne {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.SetTeammateID(v)
	})
}

// UpdateTeammateID sets the "teammate_id" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsertOne) UpdateTeammateID() *ArchivedTaskActivityUpsertOne {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.UpdateTeammateID()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *ArchivedTaskActivityUpsertOne) SetWorkspaceID(v ulid.ID) *ArchivedTaskActivityUpsertOne {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsertOne) UpdateWorkspaceID() *ArchivedTaskActivityUpsertOne {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ArchivedTaskActivityUpsertOne) SetCreatedAt(v time.Time) *ArchivedTaskActivityUpsertOne {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsertOne) UpdateCreatedAt() *ArchivedTaskActivityUpsertOne {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ArchivedTaskActivityUpsertOne) SetUpdatedAt(v time.Time) *ArchivedTaskActivityUpsertOne {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsertOne) UpdateUpdatedAt() *ArchivedTaskActivityUpsertOne {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ArchivedTaskActivityUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArchivedTaskActivityCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArchivedTaskActivityUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ArchivedTaskActivityUpsertOne) ID(ctx context.Context) (id ulid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ArchivedTaskActivityUpsertOne.ID is not supported by MySQL driver. Use ArchivedTaskActivityUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ArchivedTaskActivityUpsertOne) IDX(ctx context.Context) ulid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ArchivedTaskActivityCreateBulk is the builder for creating many ArchivedTaskActivity entities in bulk.
type ArchivedTaskActivityCreateBulk struct {
	config
	builders []*ArchivedTaskActivityCreate
	conflict []sql.ConflictOption
}

// Save creates the ArchivedTaskActivity entities in the database.
func (atacb *ArchivedTaskActivityCreateBulk) Save(ctx context.Context) ([]*ArchivedTaskActivity, error) {
	specs := make([]*sqlgraph.CreateSpec, len(atacb.builders))
	nodes := make([]*ArchivedTaskActivity, len(atacb.builders))
	mutators := make([]Mutator, len(atacb.builders))
	for i := range atacb.builders {
		func(i int, root context.Context) {
			builder := atacb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArchivedTaskActivityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, atacb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = atacb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, atacb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, atacb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (atacb *ArchivedTaskActivityCreateBulk) SaveX(ctx context.Context) []*ArchivedTaskActivity {
	v, err := atacb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (atacb *ArchivedTaskActivityCreateBulk) Exec(ctx context.Context) error {
	_, err := atacb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atacb *ArchivedTaskActivityCreateBulk) ExecX(ctx context.Context) {
	if err := atacb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ArchivedTaskActivity.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ArchivedTaskActivityUpsert) {
//			SetActivityTypeID(v+v).
//		}).
//		Exec(ctx)
//
func (atacb *ArchivedTaskActivityCreateBulk) OnConflict(opts ...sql.ConflictOption) *ArchivedTaskActivityUpsertBulk {
	atacb.conflict = opts
	return &ArchivedTaskActivityUpsertBulk{
		create: atacb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ArchivedTaskActivity.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (atacb *ArchivedTaskActivityCreateBulk) OnConflictColumns(columns ...string) *ArchivedTaskActivityUpsertBulk {
	atacb.conflict = append(atacb.conflict, sql.ConflictColumns(columns...))
	return &ArchivedTaskActivityUpsertBulk{
		create: atacb,
	}
}

// ArchivedTaskActivityUpsertBulk is the builder for "upsert"-ing
// a bulk of ArchivedTaskActivity nodes.
type ArchivedTaskActivityUpsertBulk struct {
	create *ArchivedTaskActivityCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ArchivedTaskActivity.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(archivedtaskactivity.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *ArchivedTaskActivityUpsertBulk) UpdateNewValues() *ArchivedTaskActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(archivedtaskactivity.FieldID)
				return
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(archivedtaskactivity.FieldCreatedAt)
			}
			if _, exists := b.mutation.UpdatedAt(); exists {
				s.SetIgnore(archivedtaskactivity.FieldUpdatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ArchivedTaskActivity.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *ArchivedTaskActivityUpsertBulk) Ignore() *ArchivedTaskActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ArchivedTaskActivityUpsertBulk) DoNothing() *ArchivedTaskActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ArchivedTaskActivityCreateBulk.OnConflict
// documentation for more info.
func (u *ArchivedTaskActivityUpsertBulk) Update(set func(*ArchivedTaskActivityUpsert)) *ArchivedTaskActivityUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ArchivedTaskActivityUpsert{UpdateSet: update})
	}))
	return u
}

// SetActivityTypeID sets the "activity_type_id" field.
func (u *ArchivedTaskActivityUpsertBulk) SetActivityTypeID(v ulid.ID) *ArchivedTaskActivityUpsertBulk {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.SetActivityTypeID(v)
	})
}

// UpdateActivityTypeID sets the "activity_type_id" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsertBulk) UpdateActivityTypeID() *ArchivedTaskActivityUpsertBulk {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.UpdateActivityTypeID()
	})
}

// SetTeammateID sets the "teammate_id" field.
func (u *ArchivedTaskActivityUpsertBulk) SetTeammateID(v ulid.ID) *ArchivedTaskActivityUpsertBulk {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.SetTeammateID(v)
	})
}

// UpdateTeammateID sets the "teammate_id" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsertBulk) UpdateTeammateID() *ArchivedTaskActivityUpsertBulk {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.UpdateTeammateID()
	})
}

// SetWorkspaceID sets the "workspace_id" field.
func (u *ArchivedTaskActivityUpsertBulk) SetWorkspaceID(v ulid.ID) *ArchivedTaskActivityUpsertBulk {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.SetWorkspaceID(v)
	})
}

// UpdateWorkspaceID sets the "workspace_id" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsertBulk) UpdateWorkspaceID() *ArchivedTaskActivityUpsertBulk {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.UpdateWorkspaceID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *ArchivedTaskActivityUpsertBulk) SetCreatedAt(v time.Time) *ArchivedTaskActivityUpsertBulk {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsertBulk) UpdateCreatedAt() *ArchivedTaskActivityUpsertBulk {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ArchivedTaskActivityUpsertBulk) SetUpdatedAt(v time.Time) *ArchivedTaskActivityUpsertBulk {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ArchivedTaskActivityUpsertBulk) UpdateUpdatedAt() *ArchivedTaskActivityUpsertBulk {
	return u.Update(func(s *ArchivedTaskActivityUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *ArchivedTaskActivityUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ArchivedTaskActivityCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ArchivedTaskActivityCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ArchivedTaskActivityUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
