// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"project-management-demo-backend/ent/deletedteammatetask"
	"project-management-demo-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeletedTeammateTaskDelete is the builder for deleting a DeletedTeammateTask entity.
type DeletedTeammateTaskDelete struct {
	config
	hooks    []Hook
	mutation *DeletedTeammateTaskMutation
}

// Where appends a list predicates to the DeletedTeammateTaskDelete builder.
func (dttd *DeletedTeammateTaskDelete) Where(ps ...predicate.DeletedTeammateTask) *DeletedTeammateTaskDelete {
	dttd.mutation.Where(ps...)
	return dttd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (dttd *DeletedTeammateTaskDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(dttd.hooks) == 0 {
		affected, err = dttd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DeletedTeammateTaskMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dttd.mutation = mutation
			affected, err = dttd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(dttd.hooks) - 1; i >= 0; i-- {
			if dttd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = dttd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dttd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (dttd *DeletedTeammateTaskDelete) ExecX(ctx context.Context) int {
	n, err := dttd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (dttd *DeletedTeammateTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: deletedteammatetask.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: deletedteammatetask.FieldID,
			},
		},
	}
	if ps := dttd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, dttd.driver, _spec)
}

// DeletedTeammateTaskDeleteOne is the builder for deleting a single DeletedTeammateTask entity.
type DeletedTeammateTaskDeleteOne struct {
	dttd *DeletedTeammateTaskDelete
}

// Exec executes the deletion query.
func (dttdo *DeletedTeammateTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := dttdo.dttd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{deletedteammatetask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dttdo *DeletedTeammateTaskDeleteOne) ExecX(ctx context.Context) {
	dttdo.dttd.ExecX(ctx)
}
