// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"project-management-demo-backend/ent/schema/ulid"
	"project-management-demo-backend/ent/task"
	"project-management-demo-backend/ent/taskactivity"
	"project-management-demo-backend/ent/taskactivitytask"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskActivityTaskCreate is the builder for creating a TaskActivityTask entity.
type TaskActivityTaskCreate struct {
	config
	mutation *TaskActivityTaskMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTaskActivityID sets the "task_activity_id" field.
func (tatc *TaskActivityTaskCreate) SetTaskActivityID(u ulid.ID) *TaskActivityTaskCreate {
	tatc.mutation.SetTaskActivityID(u)
	return tatc
}

// SetTaskID sets the "task_id" field.
func (tatc *TaskActivityTaskCreate) SetTaskID(u ulid.ID) *TaskActivityTaskCreate {
	tatc.mutation.SetTaskID(u)
	return tatc
}

// SetCreatedAt sets the "created_at" field.
func (tatc *TaskActivityTaskCreate) SetCreatedAt(t time.Time) *TaskActivityTaskCreate {
	tatc.mutation.SetCreatedAt(t)
	return tatc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tatc *TaskActivityTaskCreate) SetNillableCreatedAt(t *time.Time) *TaskActivityTaskCreate {
	if t != nil {
		tatc.SetCreatedAt(*t)
	}
	return tatc
}

// SetUpdatedAt sets the "updated_at" field.
func (tatc *TaskActivityTaskCreate) SetUpdatedAt(t time.Time) *TaskActivityTaskCreate {
	tatc.mutation.SetUpdatedAt(t)
	return tatc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tatc *TaskActivityTaskCreate) SetNillableUpdatedAt(t *time.Time) *TaskActivityTaskCreate {
	if t != nil {
		tatc.SetUpdatedAt(*t)
	}
	return tatc
}

// SetID sets the "id" field.
func (tatc *TaskActivityTaskCreate) SetID(u ulid.ID) *TaskActivityTaskCreate {
	tatc.mutation.SetID(u)
	return tatc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (tatc *TaskActivityTaskCreate) SetNillableID(u *ulid.ID) *TaskActivityTaskCreate {
	if u != nil {
		tatc.SetID(*u)
	}
	return tatc
}

// SetTask sets the "task" edge to the Task entity.
func (tatc *TaskActivityTaskCreate) SetTask(t *Task) *TaskActivityTaskCreate {
	return tatc.SetTaskID(t.ID)
}

// SetTaskActivity sets the "taskActivity" edge to the TaskActivity entity.
func (tatc *TaskActivityTaskCreate) SetTaskActivity(t *TaskActivity) *TaskActivityTaskCreate {
	return tatc.SetTaskActivityID(t.ID)
}

// Mutation returns the TaskActivityTaskMutation object of the builder.
func (tatc *TaskActivityTaskCreate) Mutation() *TaskActivityTaskMutation {
	return tatc.mutation
}

// Save creates the TaskActivityTask in the database.
func (tatc *TaskActivityTaskCreate) Save(ctx context.Context) (*TaskActivityTask, error) {
	var (
		err  error
		node *TaskActivityTask
	)
	tatc.defaults()
	if len(tatc.hooks) == 0 {
		if err = tatc.check(); err != nil {
			return nil, err
		}
		node, err = tatc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TaskActivityTaskMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tatc.check(); err != nil {
				return nil, err
			}
			tatc.mutation = mutation
			if node, err = tatc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tatc.hooks) - 1; i >= 0; i-- {
			if tatc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tatc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tatc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tatc *TaskActivityTaskCreate) SaveX(ctx context.Context) *TaskActivityTask {
	v, err := tatc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tatc *TaskActivityTaskCreate) Exec(ctx context.Context) error {
	_, err := tatc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tatc *TaskActivityTaskCreate) ExecX(ctx context.Context) {
	if err := tatc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tatc *TaskActivityTaskCreate) defaults() {
	if _, ok := tatc.mutation.CreatedAt(); !ok {
		v := taskactivitytask.DefaultCreatedAt()
		tatc.mutation.SetCreatedAt(v)
	}
	if _, ok := tatc.mutation.UpdatedAt(); !ok {
		v := taskactivitytask.DefaultUpdatedAt()
		tatc.mutation.SetUpdatedAt(v)
	}
	if _, ok := tatc.mutation.ID(); !ok {
		v := taskactivitytask.DefaultID()
		tatc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tatc *TaskActivityTaskCreate) check() error {
	if _, ok := tatc.mutation.TaskActivityID(); !ok {
		return &ValidationError{Name: "task_activity_id", err: errors.New(`ent: missing required field "TaskActivityTask.task_activity_id"`)}
	}
	if _, ok := tatc.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "TaskActivityTask.task_id"`)}
	}
	if _, ok := tatc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TaskActivityTask.created_at"`)}
	}
	if _, ok := tatc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TaskActivityTask.updated_at"`)}
	}
	if _, ok := tatc.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "TaskActivityTask.task"`)}
	}
	if _, ok := tatc.mutation.TaskActivityID(); !ok {
		return &ValidationError{Name: "taskActivity", err: errors.New(`ent: missing required edge "TaskActivityTask.taskActivity"`)}
	}
	return nil
}

func (tatc *TaskActivityTaskCreate) sqlSave(ctx context.Context) (*TaskActivityTask, error) {
	_node, _spec := tatc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tatc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*ulid.ID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (tatc *TaskActivityTaskCreate) createSpec() (*TaskActivityTask, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskActivityTask{config: tatc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: taskactivitytask.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: taskactivitytask.FieldID,
			},
		}
	)
	_spec.OnConflict = tatc.conflict
	if id, ok := tatc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := tatc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: taskactivitytask.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := tatc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: taskactivitytask.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if nodes := tatc.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskactivitytask.TaskTable,
			Columns: []string{taskactivitytask.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: task.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tatc.mutation.TaskActivityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   taskactivitytask.TaskActivityTable,
			Columns: []string{taskactivitytask.TaskActivityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: taskactivity.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskActivityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskActivityTask.Create().
//		SetTaskActivityID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskActivityTaskUpsert) {
//			SetTaskActivityID(v+v).
//		}).
//		Exec(ctx)
//
func (tatc *TaskActivityTaskCreate) OnConflict(opts ...sql.ConflictOption) *TaskActivityTaskUpsertOne {
	tatc.conflict = opts
	return &TaskActivityTaskUpsertOne{
		create: tatc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskActivityTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (tatc *TaskActivityTaskCreate) OnConflictColumns(columns ...string) *TaskActivityTaskUpsertOne {
	tatc.conflict = append(tatc.conflict, sql.ConflictColumns(columns...))
	return &TaskActivityTaskUpsertOne{
		create: tatc,
	}
}

type (
	// TaskActivityTaskUpsertOne is the builder for "upsert"-ing
	//  one TaskActivityTask node.
	TaskActivityTaskUpsertOne struct {
		create *TaskActivityTaskCreate
	}

	// TaskActivityTaskUpsert is the "OnConflict" setter.
	TaskActivityTaskUpsert struct {
		*sql.UpdateSet
	}
)

// SetTaskActivityID sets the "task_activity_id" field.
func (u *TaskActivityTaskUpsert) SetTaskActivityID(v ulid.ID) *TaskActivityTaskUpsert {
	u.Set(taskactivitytask.FieldTaskActivityID, v)
	return u
}

// UpdateTaskActivityID sets the "task_activity_id" field to the value that was provided on create.
func (u *TaskActivityTaskUpsert) UpdateTaskActivityID() *TaskActivityTaskUpsert {
	u.SetExcluded(taskactivitytask.FieldTaskActivityID)
	return u
}

// SetTaskID sets the "task_id" field.
func (u *TaskActivityTaskUpsert) SetTaskID(v ulid.ID) *TaskActivityTaskUpsert {
	u.Set(taskactivitytask.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskActivityTaskUpsert) UpdateTaskID() *TaskActivityTaskUpsert {
	u.SetExcluded(taskactivitytask.FieldTaskID)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *TaskActivityTaskUpsert) SetCreatedAt(v time.Time) *TaskActivityTaskUpsert {
	u.Set(taskactivitytask.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TaskActivityTaskUpsert) UpdateCreatedAt() *TaskActivityTaskUpsert {
	u.SetExcluded(taskactivitytask.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskActivityTaskUpsert) SetUpdatedAt(v time.Time) *TaskActivityTaskUpsert {
	u.Set(taskactivitytask.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskActivityTaskUpsert) UpdateUpdatedAt() *TaskActivityTaskUpsert {
	u.SetExcluded(taskactivitytask.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TaskActivityTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskactivitytask.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *TaskActivityTaskUpsertOne) UpdateNewValues() *TaskActivityTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(taskactivitytask.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(taskactivitytask.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.UpdatedAt(); exists {
			s.SetIgnore(taskactivitytask.FieldUpdatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.TaskActivityTask.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *TaskActivityTaskUpsertOne) Ignore() *TaskActivityTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskActivityTaskUpsertOne) DoNothing() *TaskActivityTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskActivityTaskCreate.OnConflict
// documentation for more info.
func (u *TaskActivityTaskUpsertOne) Update(set func(*TaskActivityTaskUpsert)) *TaskActivityTaskUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskActivityTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskActivityID sets the "task_activity_id" field.
func (u *TaskActivityTaskUpsertOne) SetTaskActivityID(v ulid.ID) *TaskActivityTaskUpsertOne {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.SetTaskActivityID(v)
	})
}

// UpdateTaskActivityID sets the "task_activity_id" field to the value that was provided on create.
func (u *TaskActivityTaskUpsertOne) UpdateTaskActivityID() *TaskActivityTaskUpsertOne {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.UpdateTaskActivityID()
	})
}

// SetTaskID sets the "task_id" field.
func (u *TaskActivityTaskUpsertOne) SetTaskID(v ulid.ID) *TaskActivityTaskUpsertOne {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskActivityTaskUpsertOne) UpdateTaskID() *TaskActivityTaskUpsertOne {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.UpdateTaskID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TaskActivityTaskUpsertOne) SetCreatedAt(v time.Time) *TaskActivityTaskUpsertOne {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TaskActivityTaskUpsertOne) UpdateCreatedAt() *TaskActivityTaskUpsertOne {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskActivityTaskUpsertOne) SetUpdatedAt(v time.Time) *TaskActivityTaskUpsertOne {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskActivityTaskUpsertOne) UpdateUpdatedAt() *TaskActivityTaskUpsertOne {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TaskActivityTaskUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskActivityTaskCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskActivityTaskUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TaskActivityTaskUpsertOne) ID(ctx context.Context) (id ulid.ID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TaskActivityTaskUpsertOne.ID is not supported by MySQL driver. Use TaskActivityTaskUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TaskActivityTaskUpsertOne) IDX(ctx context.Context) ulid.ID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TaskActivityTaskCreateBulk is the builder for creating many TaskActivityTask entities in bulk.
type TaskActivityTaskCreateBulk struct {
	config
	builders []*TaskActivityTaskCreate
	conflict []sql.ConflictOption
}

// Save creates the TaskActivityTask entities in the database.
func (tatcb *TaskActivityTaskCreateBulk) Save(ctx context.Context) ([]*TaskActivityTask, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tatcb.builders))
	nodes := make([]*TaskActivityTask, len(tatcb.builders))
	mutators := make([]Mutator, len(tatcb.builders))
	for i := range tatcb.builders {
		func(i int, root context.Context) {
			builder := tatcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskActivityTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tatcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tatcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tatcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tatcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tatcb *TaskActivityTaskCreateBulk) SaveX(ctx context.Context) []*TaskActivityTask {
	v, err := tatcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tatcb *TaskActivityTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := tatcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tatcb *TaskActivityTaskCreateBulk) ExecX(ctx context.Context) {
	if err := tatcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskActivityTask.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskActivityTaskUpsert) {
//			SetTaskActivityID(v+v).
//		}).
//		Exec(ctx)
//
func (tatcb *TaskActivityTaskCreateBulk) OnConflict(opts ...sql.ConflictOption) *TaskActivityTaskUpsertBulk {
	tatcb.conflict = opts
	return &TaskActivityTaskUpsertBulk{
		create: tatcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskActivityTask.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (tatcb *TaskActivityTaskCreateBulk) OnConflictColumns(columns ...string) *TaskActivityTaskUpsertBulk {
	tatcb.conflict = append(tatcb.conflict, sql.ConflictColumns(columns...))
	return &TaskActivityTaskUpsertBulk{
		create: tatcb,
	}
}

// TaskActivityTaskUpsertBulk is the builder for "upsert"-ing
// a bulk of TaskActivityTask nodes.
type TaskActivityTaskUpsertBulk struct {
	create *TaskActivityTaskCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TaskActivityTask.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskactivitytask.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *TaskActivityTaskUpsertBulk) UpdateNewValues() *TaskActivityTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(taskactivitytask.FieldID)
				return
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(taskactivitytask.FieldCreatedAt)
			}
			if _, exists := b.mutation.UpdatedAt(); exists {
				s.SetIgnore(taskactivitytask.FieldUpdatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskActivityTask.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *TaskActivityTaskUpsertBulk) Ignore() *TaskActivityTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskActivityTaskUpsertBulk) DoNothing() *TaskActivityTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskActivityTaskCreateBulk.OnConflict
// documentation for more info.
func (u *TaskActivityTaskUpsertBulk) Update(set func(*TaskActivityTaskUpsert)) *TaskActivityTaskUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskActivityTaskUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskActivityID sets the "task_activity_id" field.
func (u *TaskActivityTaskUpsertBulk) SetTaskActivityID(v ulid.ID) *TaskActivityTaskUpsertBulk {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.SetTaskActivityID(v)
	})
}

// UpdateTaskActivityID sets the "task_activity_id" field to the value that was provided on create.
func (u *TaskActivityTaskUpsertBulk) UpdateTaskActivityID() *TaskActivityTaskUpsertBulk {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.UpdateTaskActivityID()
	})
}

// SetTaskID sets the "task_id" field.
func (u *TaskActivityTaskUpsertBulk) SetTaskID(v ulid.ID) *TaskActivityTaskUpsertBulk {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.SetTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *TaskActivityTaskUpsertBulk) UpdateTaskID() *TaskActivityTaskUpsertBulk {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.UpdateTaskID()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TaskActivityTaskUpsertBulk) SetCreatedAt(v time.Time) *TaskActivityTaskUpsertBulk {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TaskActivityTaskUpsertBulk) UpdateCreatedAt() *TaskActivityTaskUpsertBulk {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TaskActivityTaskUpsertBulk) SetUpdatedAt(v time.Time) *TaskActivityTaskUpsertBulk {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TaskActivityTaskUpsertBulk) UpdateUpdatedAt() *TaskActivityTaskUpsertBulk {
	return u.Update(func(s *TaskActivityTaskUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *TaskActivityTaskUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TaskActivityTaskCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskActivityTaskCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskActivityTaskUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
