// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"
	"project-management-demo-backend/ent/predicate"
	"project-management-demo-backend/ent/schema/ulid"
	"project-management-demo-backend/ent/tasksection"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TaskSectionQuery is the builder for querying TaskSection entities.
type TaskSectionQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.TaskSection
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TaskSectionQuery builder.
func (tsq *TaskSectionQuery) Where(ps ...predicate.TaskSection) *TaskSectionQuery {
	tsq.predicates = append(tsq.predicates, ps...)
	return tsq
}

// Limit adds a limit step to the query.
func (tsq *TaskSectionQuery) Limit(limit int) *TaskSectionQuery {
	tsq.limit = &limit
	return tsq
}

// Offset adds an offset step to the query.
func (tsq *TaskSectionQuery) Offset(offset int) *TaskSectionQuery {
	tsq.offset = &offset
	return tsq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tsq *TaskSectionQuery) Unique(unique bool) *TaskSectionQuery {
	tsq.unique = &unique
	return tsq
}

// Order adds an order step to the query.
func (tsq *TaskSectionQuery) Order(o ...OrderFunc) *TaskSectionQuery {
	tsq.order = append(tsq.order, o...)
	return tsq
}

// First returns the first TaskSection entity from the query.
// Returns a *NotFoundError when no TaskSection was found.
func (tsq *TaskSectionQuery) First(ctx context.Context) (*TaskSection, error) {
	nodes, err := tsq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tasksection.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tsq *TaskSectionQuery) FirstX(ctx context.Context) *TaskSection {
	node, err := tsq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TaskSection ID from the query.
// Returns a *NotFoundError when no TaskSection ID was found.
func (tsq *TaskSectionQuery) FirstID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = tsq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tasksection.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tsq *TaskSectionQuery) FirstIDX(ctx context.Context) ulid.ID {
	id, err := tsq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TaskSection entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TaskSection entity is found.
// Returns a *NotFoundError when no TaskSection entities are found.
func (tsq *TaskSectionQuery) Only(ctx context.Context) (*TaskSection, error) {
	nodes, err := tsq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tasksection.Label}
	default:
		return nil, &NotSingularError{tasksection.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tsq *TaskSectionQuery) OnlyX(ctx context.Context) *TaskSection {
	node, err := tsq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TaskSection ID in the query.
// Returns a *NotSingularError when more than one TaskSection ID is found.
// Returns a *NotFoundError when no entities are found.
func (tsq *TaskSectionQuery) OnlyID(ctx context.Context) (id ulid.ID, err error) {
	var ids []ulid.ID
	if ids, err = tsq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tasksection.Label}
	default:
		err = &NotSingularError{tasksection.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tsq *TaskSectionQuery) OnlyIDX(ctx context.Context) ulid.ID {
	id, err := tsq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TaskSections.
func (tsq *TaskSectionQuery) All(ctx context.Context) ([]*TaskSection, error) {
	if err := tsq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tsq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tsq *TaskSectionQuery) AllX(ctx context.Context) []*TaskSection {
	nodes, err := tsq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TaskSection IDs.
func (tsq *TaskSectionQuery) IDs(ctx context.Context) ([]ulid.ID, error) {
	var ids []ulid.ID
	if err := tsq.Select(tasksection.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tsq *TaskSectionQuery) IDsX(ctx context.Context) []ulid.ID {
	ids, err := tsq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tsq *TaskSectionQuery) Count(ctx context.Context) (int, error) {
	if err := tsq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tsq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tsq *TaskSectionQuery) CountX(ctx context.Context) int {
	count, err := tsq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tsq *TaskSectionQuery) Exist(ctx context.Context) (bool, error) {
	if err := tsq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tsq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tsq *TaskSectionQuery) ExistX(ctx context.Context) bool {
	exist, err := tsq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TaskSectionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tsq *TaskSectionQuery) Clone() *TaskSectionQuery {
	if tsq == nil {
		return nil
	}
	return &TaskSectionQuery{
		config:     tsq.config,
		limit:      tsq.limit,
		offset:     tsq.offset,
		order:      append([]OrderFunc{}, tsq.order...),
		predicates: append([]predicate.TaskSection{}, tsq.predicates...),
		// clone intermediate query.
		sql:    tsq.sql.Clone(),
		path:   tsq.path,
		unique: tsq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TaskSection.Query().
//		GroupBy(tasksection.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tsq *TaskSectionQuery) GroupBy(field string, fields ...string) *TaskSectionGroupBy {
	group := &TaskSectionGroupBy{config: tsq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tsq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tsq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.TaskSection.Query().
//		Select(tasksection.FieldName).
//		Scan(ctx, &v)
//
func (tsq *TaskSectionQuery) Select(fields ...string) *TaskSectionSelect {
	tsq.fields = append(tsq.fields, fields...)
	return &TaskSectionSelect{TaskSectionQuery: tsq}
}

func (tsq *TaskSectionQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tsq.fields {
		if !tasksection.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tsq.path != nil {
		prev, err := tsq.path(ctx)
		if err != nil {
			return err
		}
		tsq.sql = prev
	}
	return nil
}

func (tsq *TaskSectionQuery) sqlAll(ctx context.Context) ([]*TaskSection, error) {
	var (
		nodes = []*TaskSection{}
		_spec = tsq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &TaskSection{config: tsq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, tsq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (tsq *TaskSectionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tsq.querySpec()
	_spec.Node.Columns = tsq.fields
	if len(tsq.fields) > 0 {
		_spec.Unique = tsq.unique != nil && *tsq.unique
	}
	return sqlgraph.CountNodes(ctx, tsq.driver, _spec)
}

func (tsq *TaskSectionQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tsq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tsq *TaskSectionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   tasksection.Table,
			Columns: tasksection.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: tasksection.FieldID,
			},
		},
		From:   tsq.sql,
		Unique: true,
	}
	if unique := tsq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tsq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tasksection.FieldID)
		for i := range fields {
			if fields[i] != tasksection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tsq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tsq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tsq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tsq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tsq *TaskSectionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tsq.driver.Dialect())
	t1 := builder.Table(tasksection.Table)
	columns := tsq.fields
	if len(columns) == 0 {
		columns = tasksection.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tsq.sql != nil {
		selector = tsq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tsq.unique != nil && *tsq.unique {
		selector.Distinct()
	}
	for _, p := range tsq.predicates {
		p(selector)
	}
	for _, p := range tsq.order {
		p(selector)
	}
	if offset := tsq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tsq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TaskSectionGroupBy is the group-by builder for TaskSection entities.
type TaskSectionGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tsgb *TaskSectionGroupBy) Aggregate(fns ...AggregateFunc) *TaskSectionGroupBy {
	tsgb.fns = append(tsgb.fns, fns...)
	return tsgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tsgb *TaskSectionGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tsgb.path(ctx)
	if err != nil {
		return err
	}
	tsgb.sql = query
	return tsgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tsgb *TaskSectionGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tsgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tsgb *TaskSectionGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tsgb.fields) > 1 {
		return nil, errors.New("ent: TaskSectionGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tsgb *TaskSectionGroupBy) StringsX(ctx context.Context) []string {
	v, err := tsgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tsgb *TaskSectionGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tsgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tasksection.Label}
	default:
		err = fmt.Errorf("ent: TaskSectionGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tsgb *TaskSectionGroupBy) StringX(ctx context.Context) string {
	v, err := tsgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tsgb *TaskSectionGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tsgb.fields) > 1 {
		return nil, errors.New("ent: TaskSectionGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tsgb *TaskSectionGroupBy) IntsX(ctx context.Context) []int {
	v, err := tsgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tsgb *TaskSectionGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tsgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tasksection.Label}
	default:
		err = fmt.Errorf("ent: TaskSectionGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tsgb *TaskSectionGroupBy) IntX(ctx context.Context) int {
	v, err := tsgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tsgb *TaskSectionGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tsgb.fields) > 1 {
		return nil, errors.New("ent: TaskSectionGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tsgb *TaskSectionGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tsgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tsgb *TaskSectionGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tsgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tasksection.Label}
	default:
		err = fmt.Errorf("ent: TaskSectionGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tsgb *TaskSectionGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tsgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tsgb *TaskSectionGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tsgb.fields) > 1 {
		return nil, errors.New("ent: TaskSectionGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tsgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tsgb *TaskSectionGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tsgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tsgb *TaskSectionGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tsgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tasksection.Label}
	default:
		err = fmt.Errorf("ent: TaskSectionGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tsgb *TaskSectionGroupBy) BoolX(ctx context.Context) bool {
	v, err := tsgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tsgb *TaskSectionGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tsgb.fields {
		if !tasksection.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tsgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tsgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tsgb *TaskSectionGroupBy) sqlQuery() *sql.Selector {
	selector := tsgb.sql.Select()
	aggregation := make([]string, 0, len(tsgb.fns))
	for _, fn := range tsgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tsgb.fields)+len(tsgb.fns))
		for _, f := range tsgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tsgb.fields...)...)
}

// TaskSectionSelect is the builder for selecting fields of TaskSection entities.
type TaskSectionSelect struct {
	*TaskSectionQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (tss *TaskSectionSelect) Scan(ctx context.Context, v interface{}) error {
	if err := tss.prepareQuery(ctx); err != nil {
		return err
	}
	tss.sql = tss.TaskSectionQuery.sqlQuery(ctx)
	return tss.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tss *TaskSectionSelect) ScanX(ctx context.Context, v interface{}) {
	if err := tss.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (tss *TaskSectionSelect) Strings(ctx context.Context) ([]string, error) {
	if len(tss.fields) > 1 {
		return nil, errors.New("ent: TaskSectionSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := tss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tss *TaskSectionSelect) StringsX(ctx context.Context) []string {
	v, err := tss.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (tss *TaskSectionSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tss.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tasksection.Label}
	default:
		err = fmt.Errorf("ent: TaskSectionSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tss *TaskSectionSelect) StringX(ctx context.Context) string {
	v, err := tss.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (tss *TaskSectionSelect) Ints(ctx context.Context) ([]int, error) {
	if len(tss.fields) > 1 {
		return nil, errors.New("ent: TaskSectionSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := tss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tss *TaskSectionSelect) IntsX(ctx context.Context) []int {
	v, err := tss.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (tss *TaskSectionSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tss.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tasksection.Label}
	default:
		err = fmt.Errorf("ent: TaskSectionSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tss *TaskSectionSelect) IntX(ctx context.Context) int {
	v, err := tss.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (tss *TaskSectionSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(tss.fields) > 1 {
		return nil, errors.New("ent: TaskSectionSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := tss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tss *TaskSectionSelect) Float64sX(ctx context.Context) []float64 {
	v, err := tss.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (tss *TaskSectionSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tss.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tasksection.Label}
	default:
		err = fmt.Errorf("ent: TaskSectionSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tss *TaskSectionSelect) Float64X(ctx context.Context) float64 {
	v, err := tss.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (tss *TaskSectionSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(tss.fields) > 1 {
		return nil, errors.New("ent: TaskSectionSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := tss.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tss *TaskSectionSelect) BoolsX(ctx context.Context) []bool {
	v, err := tss.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (tss *TaskSectionSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tss.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{tasksection.Label}
	default:
		err = fmt.Errorf("ent: TaskSectionSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tss *TaskSectionSelect) BoolX(ctx context.Context) bool {
	v, err := tss.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tss *TaskSectionSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := tss.sql.Query()
	if err := tss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
