// Generated by `yarn new:queryMock`
import type deepmerge from 'deepmerge'
import type { TaskPrioritiesQuery as Query } from 'src/graphql/types/index.mock'
import type { DeepPartial } from 'utility-types'

export type Response = DeepPartial<Query>
export type { TaskPrioritiesQuery as Query } from 'src/graphql/types/index.mock'

export type Options = {
  res?: Response
  networkError?: boolean
  deepMergeOptions?: deepmerge.Options
}
