subscription ProjectTaskCreatedByTaskId(
  $workspaceId: ID!
  $requestId: String!
) {
  projectTaskCreatedByTaskId(workspaceId: $workspaceId, requestId: $requestId) {
    ...ProjectTaskFragment
  }
}
