subscription TeammateTaskUpdated(
  $workspaceId: ID!
  $teammateId: ID!
  $requestId: String!
) {
  teammateTaskUpdated(
    teammateId: $teammateId
    workspaceId: $workspaceId
    requestId: $requestId
  ) {
    ...TeammateTaskFragment
  }
}
