subscription teammateTaskSectionDeletedAndKeepTasks(
  $teammateId: ID!
  $workspaceId: ID!
  $requestId: String!
) {
  teammateTaskSectionDeletedAndKeepTasks(
    teammateId: $teammateId
    workspaceId: $workspaceId
    requestId: $requestId
  ) {
    teammateTaskSection {
      id
    }
    keptTeammateTaskSection {
      id
    }
    teammateTaskIds
  }
}
