subscription ProjectTaskSectionUpdated($workspaceId: ID!, $requestId: String!) {
  projectTaskSectionUpdated(workspaceId: $workspaceId, requestId: $requestId) {
    ...ProjectTaskSectionFragment
  }
}
