subscription ProjectTaskSectionUndeletedAndDeleteTasks($workspaceId: ID!, $requestId: String!) {
  projectTaskSectionUndeletedAndDeleteTasks(workspaceId: $workspaceId, requestId: $requestId) {
    projectTaskSection {
      ...ProjectTaskSectionFragment
    }
  }
}
