subscription ProjectTaskSectionCreated($workspaceId: ID!, $requestId: String!) {
  projectTaskSectionCreated(workspaceId: $workspaceId, requestId: $requestId) {
    ...ProjectTaskSectionFragment
  }
}
