subscription projectTaskSectionDeletedAndDeleteTasks(
  $workspaceId: ID!
  $requestId: String!
) {
  projectTaskSectionDeletedAndDeleteTasks(
    workspaceId: $workspaceId
    requestId: $requestId
  ) {
    projectTaskSection {
      id
    }
    projectTaskIds
  }
}
