subscription TaskUndeleted($workspaceId: ID!, $requestId: String!) {
  taskUndeleted(workspaceId: $workspaceId, requestId: $requestId) {
    teammateTask {
      ...TeammateTaskFragment
    }
    projectTask {
      ...ProjectTaskFragment
    }
    deletedTasks {
      id
    }
  }
}
