subscription TaskDeleted($workspaceId: ID!, $requestId: String!) {
  taskDeleted(workspaceId: $workspaceId, requestId: $requestId) {
    teammateTask {
      id
    }
    projectTask {
      id
    }
    deletedTasks {
      ...DeletedTaskFragment
    }
  }
}
