subscription teammateTaskSectionDeletedAndDeleteTasks($teammateId: ID!, $workspaceId: ID!, $requestId: String!) {
  teammateTaskSectionDeletedAndDeleteTasks(teammateId: $teammateId, workspaceId: $workspaceId, requestId: $requestId) {
    teammateTaskSection {
      id
    }
    teammateTaskIds
  }
}
