subscription TeammateTaskSectionDeleted(
  $teammateId: ID!
  $workspaceId: ID!
  $requestId: String!
) {
  teammateTaskSectionDeleted(
    teammateId: $teammateId
    workspaceId: $workspaceId
    requestId: $requestId
  ) {
    id
  }
}
