subscription TeammateTaskSectionUpdated($workspaceId: ID!, $requestId: String!) {
  teammateTaskSectionUpdated(workspaceId: $workspaceId, requestId: $requestId) {
    ...TeammateTaskSectionFragment
  }
}
