subscription TeammateTaskCreated($workspaceId: ID!, $teammateId: ID!, $requestId: String!) {
  teammateTaskCreated(teammateId: $teammateId, workspaceId: $workspaceId, requestId: $requestId) {
    ...TeammateTaskFragment
  }
}
