subscription TeammateTaskSectionUndeletedAndDeleteTasks($teammateId: ID!, $workspaceId: ID!, $requestId: String!) {
  teammateTaskSectionUndeletedAndDeleteTasks(teammateId: $teammateId, workspaceId: $workspaceId, requestId: $requestId) {
    teammateTaskSection {
      ...TeammateTaskSectionFragment
    }
  }
}
