query WorkspacePage {
  workspace(where: { name: "My Workspace" }) {
    ...WorkspaceFragment
    projects {
      ...ProjectFragment
    }
    workspaceTeammates {
      ...WorkspaceTeammateFragment
    }
  }
}
