export const config = {
  APP_ENV: process.env.NEXT_PUBLIC_APP_ENV!,
  API_URL: process.env.NEXT_PUBLIC_API_URL!,
  API_SUBSCRIPTION_URL: process.env.NEXT_PUBLIC_API_SUBSCRIPTION_URL!,
  FIREBASE_API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY!,
  FIREBASE_AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN!,
  FIREBASE_DATABASE_URL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL!,
  FIREBASE_PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID!,
  FIREBASE_STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET!,
  FIREBASE_MESSAGING_SENDER_ID:
    process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID!,
  FIREBASE_APPID: process.env.NEXT_PUBLIC_FIREBASE_APPID!,
  FIREBASE_MEASUREMENT_ID: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID!,
} as const

if (__DEV__ && process.env.NODE_ENV !== 'test') {
  console.groupCollapsed('config')
  console.log(config)
  console.groupEnd()
}
