fragment ProjectTaskColumnFragment on ProjectTaskColumn {
  id
  projectId
  width
  disabled
  customizable
  order
  taskColumnId
  taskColumn {
    ...TaskColumnFragment
  }
  createdAt
  updatedAt
}
