fragment ProjectFragment on Project {
  id
  name
  projectBaseColorId
  projectLightColorId
  projectIconId
  description
  descriptionTitle
  teammateIds
  projectTeammates {
    ...ProjectTeammateFragment
  }
  dueDate
  createdBy
  createdAt
  updatedAt
}
