fragment SubTaskFragment on Task {
  id
  name
  assigneeId
  taskFeeds {
    ...TaskFeedFragment
  }
  taskFiles {
    ...TaskFileFragment
  }
  taskTags {
    ...TaskTagFragment
  }
  taskPriority {
    ...TaskPriorityFragment
  }
  taskCollaborators {
    ...TaskCollaboratorFragment
  }
  projectTasks {
    id
    taskId
    projectId
    project {
      ...ProjectFragment
    }
    createdAt
    updatedAt
  }
  isNew
  taskParentId
  completedAt
  completed
  taskPriorityId
  dueDate
  dueTime
  createdBy
  createdAt
  updatedAt
}
