fragment TaskFragment on Task {
  id
  name
  description {
    ...DescriptionFragment
  }
  assigneeId
  taskFeeds {
    ...TaskFeedFragment
  }
  taskLikes {
    ...TaskLikeFragment
  }
  taskFeedLikes {
    ...TaskFeedLikeFragment
  }
  taskFiles {
    ...TaskFileFragment
  }
  taskTags {
    ...TaskTagFragment
  }
  taskPriority {
    ...TaskPriorityFragment
  }
  taskCollaborators {
    ...TaskCollaboratorFragment
  }
  subTasks {
    ...SubTaskFragment
  }
  projectTasks {
    id
    taskId
    projectId
    projectTaskSectionId
    project {
      ...ProjectFragment
    }
    createdAt
    updatedAt
  }
  isNew
  taskParentId
  completedAt
  completed
  taskPriorityId
  dueDate
  dueTime
  createdBy
  createdAt
  updatedAt
}
