// Code generated by entc, DO NOT EDIT.

package taskactivitytask

import (
	"project-management-demo-backend/ent/schema/ulid"
	"time"
)

const (
	// Label holds the string label denoting the taskactivitytask type in the database.
	Label = "task_activity_task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskActivityID holds the string denoting the task_activity_id field in the database.
	FieldTaskActivityID = "task_activity_id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeTask holds the string denoting the task edge name in mutations.
	EdgeTask = "task"
	// EdgeTaskActivity holds the string denoting the taskactivity edge name in mutations.
	EdgeTaskActivity = "taskActivity"
	// Table holds the table name of the taskactivitytask in the database.
	Table = "task_activity_tasks"
	// TaskTable is the table that holds the task relation/edge.
	TaskTable = "task_activity_tasks"
	// TaskInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TaskInverseTable = "tasks"
	// TaskColumn is the table column denoting the task relation/edge.
	TaskColumn = "task_id"
	// TaskActivityTable is the table that holds the taskActivity relation/edge.
	TaskActivityTable = "task_activity_tasks"
	// TaskActivityInverseTable is the table name for the TaskActivity entity.
	// It exists in this package in order to avoid circular dependency with the "taskactivity" package.
	TaskActivityInverseTable = "task_activities"
	// TaskActivityColumn is the table column denoting the taskActivity relation/edge.
	TaskActivityColumn = "task_activity_id"
)

// Columns holds all SQL columns for taskactivitytask fields.
var Columns = []string{
	FieldID,
	FieldTaskActivityID,
	FieldTaskID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() ulid.ID
)
