import {
  TASK_LIST_COMPLETED_STATUS_TYPE_INCOMPLETE,
  TASK_LIST_COMPLETED_STATUS_TYPE_COMPLETED,
  TASK_LIST_COMPLETED_STATUS_TYPE_COMPLETED_TODAY,
  TASK_LIST_COMPLETED_STATUS_TYPE_COMPLETED_YESTERDAY,
  TASK_LIST_COMPLETED_STATUS_TYPE_COMPLETED_1_WEEK,
  TASK_LIST_COMPLETED_STATUS_TYPE_COMPLETED_2_WEEKS,
  TASK_LIST_COMPLETED_STATUS_TYPE_COMPLETED_3_WEEKS,
  TASK_LIST_COMPLETED_STATUS_TYPE_ALL,
  TASK_LIST_SORT_STATUS_TYPE_NONE,
  TASK_LIST_SORT_STATUS_TYPE_DUE_DATE,
  TASK_LIST_SORT_STATUS_TYPE_LIKES,
  TASK_LIST_SORT_STATUS_TYPE_ALPHABETICAL,
  TASK_LIST_SORT_STATUS_TYPE_ASSIGNEE,
} from 'src/store/entities/taskListStatus'

export type TaskListCompletedStatusType =
  | typeof TASK_LIST_COMPLETED_STATUS_TYPE_INCOMPLETE
  | typeof TASK_LIST_COMPLETED_STATUS_TYPE_COMPLETED
  | typeof TASK_LIST_COMPLETED_STATUS_TYPE_COMPLETED_TODAY
  | typeof TASK_LIST_COMPLETED_STATUS_TYPE_COMPLETED_YESTERDAY
  | typeof TASK_LIST_COMPLETED_STATUS_TYPE_COMPLETED_1_WEEK
  | typeof TASK_LIST_COMPLETED_STATUS_TYPE_COMPLETED_2_WEEKS
  | typeof TASK_LIST_COMPLETED_STATUS_TYPE_COMPLETED_3_WEEKS
  | typeof TASK_LIST_COMPLETED_STATUS_TYPE_ALL

export type TaskListSortStatusType =
  | typeof TASK_LIST_SORT_STATUS_TYPE_NONE
  | typeof TASK_LIST_SORT_STATUS_TYPE_DUE_DATE
  | typeof TASK_LIST_SORT_STATUS_TYPE_LIKES
  | typeof TASK_LIST_SORT_STATUS_TYPE_ALPHABETICAL
  | typeof TASK_LIST_SORT_STATUS_TYPE_ASSIGNEE
