// Code generated by entc, DO NOT EDIT.

package workspaceactivity

import (
	"project-management-demo-backend/ent/schema/ulid"
	"time"
)

const (
	// Label holds the string label denoting the workspaceactivity type in the database.
	Label = "workspace_activity"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldActivityTypeID holds the string denoting the activity_type_id field in the database.
	FieldActivityTypeID = "activity_type_id"
	// FieldWorkspaceID holds the string denoting the workspace_id field in the database.
	FieldWorkspaceID = "workspace_id"
	// FieldProjectID holds the string denoting the project_id field in the database.
	FieldProjectID = "project_id"
	// FieldTeammateID holds the string denoting the teammate_id field in the database.
	FieldTeammateID = "teammate_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeActivityType holds the string denoting the activitytype edge name in mutations.
	EdgeActivityType = "activityType"
	// EdgeWorkspace holds the string denoting the workspace edge name in mutations.
	EdgeWorkspace = "workspace"
	// EdgeProject holds the string denoting the project edge name in mutations.
	EdgeProject = "project"
	// EdgeTeammate holds the string denoting the teammate edge name in mutations.
	EdgeTeammate = "teammate"
	// EdgeWorkspaceActivityTasks holds the string denoting the workspaceactivitytasks edge name in mutations.
	EdgeWorkspaceActivityTasks = "workspaceActivityTasks"
	// Table holds the table name of the workspaceactivity in the database.
	Table = "workspace_activities"
	// ActivityTypeTable is the table that holds the activityType relation/edge.
	ActivityTypeTable = "workspace_activities"
	// ActivityTypeInverseTable is the table name for the ActivityType entity.
	// It exists in this package in order to avoid circular dependency with the "activitytype" package.
	ActivityTypeInverseTable = "activity_types"
	// ActivityTypeColumn is the table column denoting the activityType relation/edge.
	ActivityTypeColumn = "activity_type_id"
	// WorkspaceTable is the table that holds the workspace relation/edge.
	WorkspaceTable = "workspace_activities"
	// WorkspaceInverseTable is the table name for the Workspace entity.
	// It exists in this package in order to avoid circular dependency with the "workspace" package.
	WorkspaceInverseTable = "workspaces"
	// WorkspaceColumn is the table column denoting the workspace relation/edge.
	WorkspaceColumn = "workspace_id"
	// ProjectTable is the table that holds the project relation/edge.
	ProjectTable = "workspace_activities"
	// ProjectInverseTable is the table name for the Project entity.
	// It exists in this package in order to avoid circular dependency with the "project" package.
	ProjectInverseTable = "projects"
	// ProjectColumn is the table column denoting the project relation/edge.
	ProjectColumn = "project_id"
	// TeammateTable is the table that holds the teammate relation/edge.
	TeammateTable = "workspace_activities"
	// TeammateInverseTable is the table name for the Teammate entity.
	// It exists in this package in order to avoid circular dependency with the "teammate" package.
	TeammateInverseTable = "teammates"
	// TeammateColumn is the table column denoting the teammate relation/edge.
	TeammateColumn = "teammate_id"
	// WorkspaceActivityTasksTable is the table that holds the workspaceActivityTasks relation/edge.
	WorkspaceActivityTasksTable = "workspace_activity_tasks"
	// WorkspaceActivityTasksInverseTable is the table name for the WorkspaceActivityTask entity.
	// It exists in this package in order to avoid circular dependency with the "workspaceactivitytask" package.
	WorkspaceActivityTasksInverseTable = "workspace_activity_tasks"
	// WorkspaceActivityTasksColumn is the table column denoting the workspaceActivityTasks relation/edge.
	WorkspaceActivityTasksColumn = "workspace_activity_id"
)

// Columns holds all SQL columns for workspaceactivity fields.
var Columns = []string{
	FieldID,
	FieldActivityTypeID,
	FieldWorkspaceID,
	FieldProjectID,
	FieldTeammateID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() ulid.ID
)
