query ProjectLightColors($after: Cursor, $before: Cursor, $first: Int, $last: Int, $where: ProjectLightColorWhereInput) {
  projectLightColors(after: $after, before: $before, first: $first, last: $last, where: $where) {
    edges {
      node {
        ...ProjectLightColorFragment
      }
    }
  }
}
