name: asana-clone-app
services:
  mysql:
    container_name: mysql
    image: mysql:8.0.23
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_as_ci --default-authentication-plugin=mysql_native_password
    environment:
      TZ:  "/usr/share/zoneinfo/Asia/Tokyo"
      MYSQL_ROOT_PASSWORD: root

    ports:
      - '3308:3306'
  redis:
    container_name: redis
    image: redis:5.0.7
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
